services:
  a0-dev-test2:
    container_name: A0-dev-test2
    build:
      context: .
      dockerfile: DockerfileLocal
    volumes:
      - ./:/a0
    ports:
      - "8891:80"
    environment:
      - A0_BUILD_VERSION=AS v0.9.9-standard-pre 2026-05-02
    restart: unless-stopped








