name: a0-merge-test

services:
  a0-merge-test:
    container_name: A0-merge-test
    build:
      context: .
      dockerfile: DockerfileLocal
      args:
        BRANCH: local
        BUILD_VARIANT: fullGPU
        PYTORCH_VARIANT: cuda
        BUILD_VERSION_ID: ${A0_FULLGPU_VERSION_ID:-v0.9.9-gpu-pre}
        CACHE_DATE: ${CACHE_DATE:-none}
    ports:
      - "8896:80"
    environment:
      - BUILD_VARIANT=fullGPU
      - PYTORCH_VARIANT=cuda
    volumes:
      - ./webui:/a0/webui
      - ./python:/a0/python
      - ./models.py:/a0/models.py
      - ./conf:/a0/conf
      - ./config:/a0/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
